package exporter_test

import (
	"context"
	"testing"

	"github.com/bonarizki-dat/go-excel/excel"
	"github.com/bonarizki-dat/go-excel/excel/config"
	"github.com/bonarizki-dat/go-excel/excel/exporter"
)

// TestExporter_WithProperties_AppliesDocProps verifies Export sets the
// workbook's OOXML core document properties from WithProperties.
func TestExporter_WithProperties_AppliesDocProps(t *testing.T) {
	props := excel.DocProperties{
		Title:       "Quarterly Report",
		Subject:     "Sales",
		Creator:     "Test Suite",
		Keywords:    "sales,report",
		Description: "Generated by a test",
		Category:    "Reports",
		Version:     "1.0.0",
	}

	exp := exporter.NewExporter([][]any{{"a"}}, excel.WithProperties(props))
	if err := exp.Export(context.Background()); err != nil {
		t.Fatalf("Export: %v", err)
	}

	got, err := exp.GetFile().GetDocProps()
	if err != nil {
		t.Fatalf("GetDocProps: %v", err)
	}
	if got.Title != props.Title || got.Subject != props.Subject || got.Creator != props.Creator ||
		got.Keywords != props.Keywords || got.Description != props.Description ||
		got.Category != props.Category || got.Version != props.Version {
		t.Errorf("doc props = %+v, want the values passed to WithProperties (%+v)", got, props)
	}
}

// TestExporter_WithProperties_Unset_LeavesExcelizeDefaults verifies
// that leaving WithProperties unset (the zero-value DocProperties)
// does not call SetDocProps at all, so Export still succeeds and
// excelize's own defaults are left in place.
func TestExporter_WithProperties_Unset_LeavesExcelizeDefaults(t *testing.T) {
	exp := exporter.NewExporter([][]any{{"a"}})
	if err := exp.Export(context.Background()); err != nil {
		t.Fatalf("Export: %v", err)
	}
	if _, err := exp.GetFile().GetDocProps(); err != nil {
		t.Fatalf("GetDocProps: %v", err)
	}
}

// TestExportToSheets_WithProperties_AppliesDocProps verifies
// ExportToSheets, which builds its workbook through a different path
// than Export, also applies WithProperties.
func TestExportToSheets_WithProperties_AppliesDocProps(t *testing.T) {
	props := excel.DocProperties{Title: "Multi-Sheet Report"}

	exp := exporter.NewExporter(nil, excel.WithProperties(props))
	sheets := []excel.Sheet{{Name: "Sheet1", Data: [][]any{{"a"}}}}
	if err := exp.ExportToSheets(context.Background(), sheets, excel.DefaultMultiSheetExportOptions()); err != nil {
		t.Fatalf("ExportToSheets: %v", err)
	}

	got, err := exp.GetFile().GetDocProps()
	if err != nil {
		t.Fatalf("GetDocProps: %v", err)
	}
	if got.Title != props.Title {
		t.Errorf("Title = %q, want %q", got.Title, props.Title)
	}
}

// TestExporter_WithProperties_IgnoredForCSV verifies WithProperties has
// no effect on CSV export and is reported by the CSV-degradation
// warning instead of failing the export.
func TestExporter_WithProperties_IgnoredForCSV(t *testing.T) {
	logger := &startCellWarnLogger{}
	exp := exporter.NewExporter([][]any{{"a"}},
		excel.WithFormat(config.FileFormatCSV),
		excel.WithProperties(excel.DocProperties{Title: "Ignored"}),
		excel.WithLogger(logger),
	)

	if _, err := exp.ExportToBuffer(context.Background()); err != nil {
		t.Fatalf("ExportToBuffer: %v", err)
	}

	found := false
	for _, f := range logger.features {
		if f == "document properties" {
			found = true
		}
	}
	if !found {
		t.Errorf("warned features = %v, want to include %q", logger.features, "document properties")
	}
}
